### ISSUE TITLE
Check unique fields with updates

### ISSUE THREAD

**Issue by alexshin** [toopay/gas-orm#14]
I created table "brands":
- id
- url
- ...

And wrote in model:
class Brand{
    function _init(){
        ...
        $this->_unique_fields(array('url'));
    }
}

When I add new record with "insert" with dublicate "url" field I give ..->errors(), but when I update existing record ..->errors() consist empty array but ..->save(true) === 0

**Comment by toopay** [comment]
Unique fields were only works on INSERT operation. There is no need to check whether the corresponding fields are unique or not, in update process (since it assume, you will not have to change those unique fields within update operation).

If you need more advance logic within your update process, use callback (refer : http://gasorm-doc.taufanaditya.com/callbacks.html)

**Comment by alexshin** [comment]
ok, but validations of update's operations return false if unique field already exists.

I used to use next constructions:
"select count(_) from table where field=`value`" for insert
"select count(_) from table where field=`value` and pk<>`id`" for update

Is it make sence?

**Comment by toopay** [comment]
`ok, but validations of update's operations return false if unique field already exists.` As i stated above, internally, Gas only perform field unique validation within INSERT operation. It do nothing, within UPDATE process, because it assume, you would not have to change those unique field(s). Personally, when doing UPDATE, i ussually have something like :

```
$user = Gas::factory('user')->find(1);
$user->name = 'Updated name';
$user->save();
```

Thats all. By above example, it clearly mean, that i will never let user to change field which supposed unchanged (either because it primary key, or either it was a unique field : like `username` for example).

So in this scenario, validation has been done in application level (my update form, in this scenario, never contain `username` field, to prevent user change something which supposed to be unchanged).

Now, could i close this issue? :)

**Comment by alexshin** [comment]
of course =)
